# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanowisko', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=20)),
                ('branza', models.ManyToManyField(related_name='branze', related_query_name='branza', to='add_job.Branza')),
            ],
        ),
    ]
