# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0002_remove_job_branza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branza',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['stanowisko']},
        ),
    ]
