# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0003_auto_20160130_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branza',
            field=models.ManyToManyField(related_name='branze', related_query_name='branza', to='add_job.Branza'),
        ),
    ]
