# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0004_job_branza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.RenameField(
            model_name='job',
            old_name='branza',
            new_name='branze',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(max_length=20, to='add_job.Tag'),
        ),
    ]
