# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0005_auto_20160130_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='opis',
            field=models.TextField(help_text='min. 200 znakow', max_length=400, validators=[django.core.validators.MinLengthValidator(200)], verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stanowisko',
            field=models.CharField(max_length=100, verbose_name='stanowisko'),
        ),
    ]
