# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_job', '0006_auto_20160131_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['stanowisko'], 'verbose_name': 'stanowisko', 'verbose_name_plural': 'stanowiska'},
        ),
    ]
